import "~/styles/globals.css";

import { Toaster } from "@/components/ui/toaster";
import { GeistSans } from "geist/font/sans";
import type { Metadata } from "next";
import { ThemeProvider } from "~/components/theme-provider";
import { CopyProvider } from "~/components/ui/copy-provider";
import { TRPCReactProvider } from "~/trpc/react";

export const metadata: Metadata = {
  title: "Smart Split",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/handshake.svg" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      {/* React scan code snippet */}
      {/* <head>
        <script src="https://unpkg.com/react-scan/dist/auto.global.js" async />
      </head> */}
      <body>
        <ThemeProvider attribute="class" defaultTheme="system">
          <CopyProvider>
            <TRPCReactProvider>{children}</TRPCReactProvider>
            <Toaster />
          </CopyProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
